#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page
# Script that installs Nginx server and redirects /redirect_me

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Timadey permanent;/" /etc/nginx/sites-available/default
service nginx start
