#!/usr/bin/env bash
# A Bash script that displays lines containing the 'bash' woed,
# shellcheck disable=SC2009
# thus allowing you to easily get the PID of your Bash process.

ps aux --forest | grep bash
