#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.

IFS=":"
while read -r uname uid gid dir login_shell; do
	echo "The user $uname is part of the $gid gang, lives in $dir and rides $login_shell. $uid's place is protected by the passcode $password, more info about the user here: $fullname";
done < /etc/passwd
