#!/usr/bin/env bash
# A Bash script that displays Best School 10 times,
#+ but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while [ $i -lt 9 ]; do
	if [ $i -eq 8 ]; then
		echo "Hi";
	fi;
	echo "Best School";
	i=$((i + 1));
done;
